export const sample_foods = [
    {
        id: '1',
        name: 'Pizza Pepporoni',
        cookTime: '10-20',
        price: 1650,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'food-1.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Meatball',
        cookTime: '20-30',
        price: 920,
        favorite: true,
        origins: ['Persia', 'middle east', 'china'],
        stars: 5,
        imageUrl: 'food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'Hamburger',
        cookTime: '10-15',
        price: 1460,
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'food-3.jpg',
        tags: ['Fastfood', 'Burger'],
    },
    {
        id: '4',
        name: 'Fried Potatoes',
        cookTime: '15-20',
        price: 880,
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3,
        imageUrl: 'food-4.jpg',
        tags: ['Fastfood', 'Fry'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        cookTime: '40-50',
        price: 1250,
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.5,
        imageUrl: 'food-5.jpg',
        tags: ['SlowFood', 'soup'],
    },
    {
        id: '6',
        name: 'Vegetable Pizza',
        cookTime: '40-50',
        price: 1580,
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'food-6.jpg',
        tags: ['Fastfood', 'Pizza', 'veg'],
    },
    {
        id: '7',
        name: 'Chicken Wrap',
        cookTime: '20-30',
        price: 1120,
        favorite: true,
        origins: ['mexico', 'monocco'],
        stars: 4.5,
        imageUrl: 'food-7.jpg',
        tags: ['Fastfood', 'Wrap',],
    },
    {
        id: '8',
        name: 'Ramen Noodles',
        cookTime: '15-20',
        price: 1420,
        favorite: true,
        origins: ['korea', 'asia'],
        stars: 4.5,
        imageUrl: 'food-8.jpg',
        tags: ['Fastfood', 'Noodles', 'Lunch'],
    },
];

export const sample_tags = [
    { name: 'All', count: 6 },
    { name: 'Fastfood', count: 4 },
    { name: 'SlowFood', count: 2 },
    { name: 'Pizza', count: 2 },
    { name: 'Noodles', count: 1 },
    { name: 'Lunch', count: 3 },
    { name: 'Burger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'soup', count: 1 },
];

export const sample_users = [
    {
        id: 1,
        name: 'John Doe',
        email: 'john@gmail.com',
        password: '12345',
        address: 'Toronto On',
        isAdmin: false,
    },
    {
        id: 2,
        name: 'Jane Doe',
        email: 'jane@gmail.com',
        password: '12345',
        address: 'Shanghai',
        isAdmin: true,
    },
];
